"""execucao e recurso

Revision ID: 90aebd305771
Revises: 
Create Date: 2026-09-25 23:22:14.143341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90aebd305771'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execucao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gerado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instante_referencia', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execucao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('chave', sa.String(length=200), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('mock', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execucao_id', 'tipo', 'chave', name='uq_recurso_item')
    )
    with op.batch_alter_table('recurso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurso_execucao_id'), ['execucao_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurso_execucao_id'))

    op.drop_table('recurso')
    op.drop_table('execucao')
    # ### end Alembic commands ###
