/**
 * Telas do protótipo O.R.A.C.U.L.O. no registro de módulos (src/modules.ts), na ordem e nos
 * grupos do menu original (02-PROTOTIPO/web/js/app.js, NAV). `ajuda` é o id da página da
 * documentação embutida (tecla F1, ./documentacao/indice.ts).
 *
 * Visão computacional tem as DUAS soluções do time lado a lado:
 * - "Visão computacional" (protótipo: detector clássico + adaptador YOLO, /api/mapa/vision);
 * - "Visão · auditoria 3 camadas" (pipeline do time: YOLOv8-seg + BDGD + cadastro ANEEL,
 *   Backend/pipeline/auditoria_*.py, /api/auditoria/mmgd).
 */
import { lazy } from 'react'
import {
  Activity,
  BatteryCharging,
  ChartPie,
  CheckCheck,
  Database,
  Eye,
  Layers,
  Link2,
  MapPin,
  Satellite,
  Scissors,
  SlidersHorizontal,
  Sun,
  Target,
  TrendingUp,
  TriangleAlert,
  ShieldCheck,
} from 'lucide-react'
import type { ModuleDef } from '../modules'

export const GRUPO_CONTRATO = 'Dashboard do contrato'

export const MODULOS_ORACULO: readonly ModuleDef[] = [
  // ---------------------------------------------------------------- Operação
  {
    path: '/operacao',
    grupo: 'Operação',
    ajuda: 'operacao',
    label: 'Despacho preditivo',
    titulo: 'Despacho preditivo',
    icone: 'wave',
    description: 'Carga medida − MMGD estimada = carga supervisionada, com banda probabilística e múltiplos horizontes',
    icon: Activity,
    Page: lazy(() => import('./pages/Operacao')),
  },
  {
    path: '/risco',
    grupo: 'Operação',
    ajuda: 'risco',
    label: 'Risco e excedentes',
    titulo: 'Risco de curtailment e excedentes',
    icone: 'alert',
    description: 'Localizar · priorizar · explicar e recomendar, com rastreabilidade até o dado de origem',
    icon: TriangleAlert,
    Page: lazy(() => import('./pages/Risco')),
  },
  {
    path: '/pato',
    grupo: 'Operação',
    ajuda: 'pato',
    label: 'Curva do pato · tempo',
    titulo: 'Curva do pato prevista pelo tempo',
    icone: 'sun',
    description: 'Radiação solar prevista por modelos de IA e físicos × onde está a MMGD → carga supervisionada dos próximos dias',
    icon: Sun,
    Page: lazy(() => import('./pages/Pato')),
  },
  // ---------------------------------------------------------------- Análise
  {
    path: '/curtailment',
    grupo: 'Análise',
    ajuda: 'curtailment',
    label: 'Curtailment',
    titulo: 'Curtailment observado',
    icone: 'cut',
    description: 'Montante, razão e origem da restrição, a partir dos registros de constrained-off do ONS',
    icon: Scissors,
    Page: lazy(() => import('./pages/Curtailment')),
  },
  {
    path: '/perfis',
    grupo: 'Análise',
    ajuda: 'perfis',
    label: 'Perfis e CLM',
    titulo: 'Perfis representativos e insumos ao CLM',
    icone: 'layers',
    description: 'Eixo 1: caracterizar perfis de consumo e a presença da geração distribuída para parametrizar modelos equivalentes',
    icon: Layers,
    Page: lazy(() => import('./pages/Perfis')),
  },
  {
    path: '/triangulacao',
    grupo: 'Análise',
    ajuda: 'triangulacao',
    label: 'Triangulação',
    titulo: 'Triangulação de evidências',
    icone: 'target',
    description: 'Três camadas independentes e a lógica de desempate que separa defasagem administrativa de instalação não homologada',
    icon: Target,
    Page: lazy(() => import('./pages/Triangulacao')),
  },
  // ---------------------------------------------------------------- Mapa Inteligente
  {
    path: '/mapa',
    grupo: 'Mapa Inteligente',
    ajuda: 'mapa',
    label: 'Perfis por subestação',
    titulo: 'Mapa Inteligente de perfis de carga e GD',
    icone: 'pin',
    description: 'Para cada subestação georreferenciada: perfil predominante de consumo e indicador de presença de geração distribuída',
    icon: MapPin,
    Page: lazy(() => import('./pages/Mapa')),
  },
  {
    path: '/visao',
    grupo: 'Mapa Inteligente',
    ajuda: 'visao',
    label: 'Visão computacional',
    titulo: 'Visão computacional sobre imagem de satélite',
    icone: 'eye',
    description: 'Detecção de painéis fotovoltaicos: pipeline, backends e desempenho medido contra verdade fundamental',
    icon: Eye,
    Page: lazy(() => import('./pages/Visao')),
  },
  {
    path: '/auditoria-mmgd',
    grupo: 'Mapa Inteligente',
    ajuda: 'auditoria',
    label: 'Visão · auditoria 3 camadas',
    titulo: 'Auditoria da MMGD em 3 camadas: satélite × BDGD × ANEEL',
    icone: 'eye',
    description: 'Painéis detectados em satélite (YOLOv8-seg) × BDGD × cadastro ANEEL: desempate e fator de correção por mancha',
    icon: Satellite,
    Page: lazy(() => import('./pages/AuditoriaMmgd')),
  },
  {
    path: '/classes',
    grupo: 'Mapa Inteligente',
    ajuda: 'classes',
    label: 'Classes de consumo',
    titulo: 'Classes de consumo e assinatura da curva',
    icone: 'pie',
    description: 'Perfis canônicos e decomposição da curva de carga verificada por mínimos quadrados não negativos',
    icon: ChartPie,
    Page: lazy(() => import('./pages/Classes')),
  },
  {
    path: '/clm',
    grupo: 'Mapa Inteligente',
    ajuda: 'clm',
    label: 'Parametrização CLM',
    titulo: 'Parametrização do Modelo de Carga Composta',
    icone: 'sliders',
    description: 'CMPLDW segundo a especificação do WECC: estrutura, equações e cartão de parâmetros com procedência campo a campo',
    icon: SlidersHorizontal,
    Page: lazy(() => import('./pages/Clm')),
  },
  // ---------------------------------------------------------------- Fronteira T–D
  {
    path: '/fronteira',
    grupo: 'Fronteira T–D',
    ajuda: 'fronteira',
    label: 'SE × distribuição',
    titulo: 'Fronteira T–D: SE da rede básica × subestação de distribuição',
    icone: 'link',
    description: 'Cada subestação de distribuição da BDGD associada à SE de fronteira do ONS que a alimenta, com a carga e a MMGD que ela leva',
    icon: Link2,
    Page: lazy(() => import('./pages/Fronteira')),
  },
  {
    path: '/correlacao',
    grupo: 'Fronteira T–D',
    ajuda: 'correlacao',
    label: 'Qualidade da correlação',
    titulo: 'Qualidade da correlação SE × SED',
    icone: 'check',
    description: 'Sem verdade de campo para a topologia: validação externa contra a carga do ONS, coerência física e sensibilidade às premissas',
    icon: CheckCheck,
    Page: lazy(() => import('./pages/Correlacao')),
  },
  // ---------------------------------------------------------------- Investimento
  {
    path: '/bess',
    grupo: 'Investimento',
    ajuda: 'bess',
    label: 'Alocação de BESS',
    titulo: 'Alocação de BESS pelo corte observado',
    icone: 'battery',
    description: 'Onde um armazenamento recupera mais energia cortada das usinas centralizadas — e quanto desse corte é excedente criado pela MMGD',
    icon: BatteryCharging,
    Page: lazy(() => import('./pages/Bess')),
  },
  {
    path: '/bess-metodo',
    grupo: 'Investimento',
    ajuda: 'bessmetodo',
    label: 'Método e sensibilidade',
    titulo: 'BESS: método, cobertura e sensibilidade',
    icone: 'sliders',
    description: 'De onde vem cada número, o que ficou de fora e o quanto o ranking depende dos pesos',
    icon: SlidersHorizontal,
    Page: lazy(() => import('./pages/BessMetodo')),
  },
  {
    path: '/projecao-ene',
    grupo: 'Investimento',
    ajuda: 'projecao',
    label: 'Projeção do corte ENE',
    titulo: 'Projeção do corte por razão energética',
    icone: 'wave',
    description: 'Quanto corte ENE vem pela frente, quanto dele a MMGD explica, e quanto BESS ele justifica no SIN',
    icon: TrendingUp,
    Page: lazy(() => import('./pages/Projecao')),
  },
  // ---------------------------------------------------------------- Confiança
  {
    path: '/validacao-metodo',
    grupo: 'Confiança',
    ajuda: 'validacao',
    label: 'Validação',
    titulo: 'Validação do método',
    icone: 'check',
    description: 'Backtest cronológico, baselines obrigatórios, métricas por patamar e calibração probabilística',
    icon: ShieldCheck,
    Page: lazy(() => import('./pages/ValidacaoMetodo')),
  },
  {
    path: '/dados-abertos',
    grupo: 'Confiança',
    ajuda: 'dados',
    label: 'Dados abertos',
    titulo: 'Dados abertos e proveniência',
    icone: 'db',
    description: 'Navegação pelo catálogo do Portal de Dados Abertos do ONS, estado do cache e rastro de cada número exibido',
    icon: Database,
    Page: lazy(() => import('./pages/DadosAbertos')),
  },
]
